### ISSUE TITLE
About the patchsize in the Generator

### ISSUE THREAD

**Issue by destructive-observer** [VITA-Group/TransGAN#32]
Dear author:
      Thanks for your job. In your model_search cifa and 256 size code ,I do not find where the patchsize use in the Generator but only in the Discriminator. Can you tell me where it is in your code? Thank you very much.

**Comment by yueruchen** [comment]
patch_size is not needed in generator

**Comment by destructive-observer** [comment]
But if do not use patch size in the G.The MLP dim will become huge when the image size becomes like 64*64. The dim will be 64*64*C,it is very large for the cuda memory, how do your resolve they problem? thank you.

**Comment by yueruchen** [comment]
that is named window_size in generator, you can try to search this term.

**Comment by destructive-observer** [comment]
Thanks for your reply, i will try it.

**Comment by RSMung** [comment]
What is window_size? I can't find it in the code of generator in ViT_custom.py

**Comment by yueruchen** [comment]
@RSMung This is because the ViT_custom.py is for cifar dataset which has 32x32 resolution that does not need window partition. Only larger resolution synthesis problem needs it and setting it to 16 should be good.

**Comment by RSMung** [comment]
Ok, I understand it. And I found that the paper which I downloaded in Summer is updated. Thank you very much!
At the same time, I have another problem: What's the difference between ViT_custom_local544444_256_rp.py and ViT_custom_local544444_256_rp_noise.py? or between ViT_custom_scale2.py and ViT_scale3_local_new_rp.py?

**Comment by RSMung** [comment]
Thank you very much!
There is another problem waiting for your help.
I found that you don't set the window_size in DisBlock when construct the Discriminator.
https://github.com/VITA-Group/TransGAN/blob/7449c76508219ccbf32e7a7047304ee6908f85c5/models_search/ViT_custom_local544444_256_rp.py#L505
This action cause a RuntimeError in my computer.
The system just point out that the shape is not match for this line:
https://github.com/VITA-Group/TransGAN/blob/7449c76508219ccbf32e7a7047304ee6908f85c5/models_search/ViT_custom_local544444_256_rp.py#L106
Error message is **RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 3**
My target resolution is 64.(Even I set the target resolution to 256, it still can't work well, the problem is same, just error message is a little different for the size.)
On the other hand, I observe that you change the window_size in Block when you construct the Generator.
https://github.com/VITA-Group/TransGAN/blob/7449c76508219ccbf32e7a7047304ee6908f85c5/models_search/ViT_custom_local544444_256_rp.py#L272
Can you help me?
Is there any problem in your code?
Should I modify the window_size when construct the Discriminator?
Wating for your reply.

**Comment by yueruchen** [comment]
It is highly depends on the specific goal of your target resolution. Regarding the 64x64 resolution, my suggestion is NOT to use grid self-attention, since the computational cost of 64x64 is affordable. The logic in this code is if you do not wish to use grid self-attention, just set the window_size equal to the feature map size. Otherwise, it will do the window partition following the window size you set
